from src.models import AnalysisReport
from src.utils import get_logger

logger = get_logger(__name__)


class ReportGenerator:
    @staticmethod
    def generate_markdown_report(report: AnalysisReport, issue_title: str) -> str:
        is_enhancement = report.issue_type == 'enhancement'
        
        # Title and header
        if is_enhancement:
            lines = [
                "# 💡 AI Feature Analysis Report",
                "",
                f"**Feature Request:** {issue_title}",
                "",
                "---",
                "",
                "## 📋 Requirements Analysis",
                "",
                report.core_analysis,
                "",
                "---",
                "",
            ]
        else:
            lines = [
                "# 🔍 AI Bug Analysis Report",
                "",
                f"**Issue:** {issue_title}",
                "",
                "---",
                "",
                "## 🎯 Root Cause Analysis",
                "",
                report.core_analysis,
                "",
                "---",
                "",
            ]
        
        if report.relevant_files:
            file_section_title = "## 📁 Files Requiring Changes" if is_enhancement else "## 📁 Relevant Files"
            lines.extend([
                file_section_title,
                "",
            ])
            for file in report.relevant_files:
                lines.append(f"### `{file.file_path}`")
                lines.append(f"**Reason:** {file.reason}")
                if file.snippet:
                    lines.extend([
                        "",
                        "```",
                        file.snippet[:500],
                        "```",
                    ])
                lines.append("")
            lines.extend(["---", ""])
        
        if report.related_issues:
            lines.extend([
                "## 🔗 Related Historical Issues",
                "",
            ])
            for issue_ref in report.related_issues:
                lines.append(f"- {issue_ref}")
            lines.extend(["", "---", ""])
        
        if report.suggested_reproduction_steps and not is_enhancement:
            lines.extend([
                "## 🔄 Reproduction Steps",
                "",
            ])
            for i, step in enumerate(report.suggested_reproduction_steps, 1):
                lines.append(f"{i}. {step}")
            lines.extend(["", "---", ""])
        
        # Implementation/Fix approach
        approach_title = "## 🚀 Recommended Implementation Approach" if is_enhancement else "## 🛠️ Recommended Fix Strategy"
        lines.extend([
            approach_title,
            "",
            report.recommended_approach,
            "",
            "---",
            "",
        ])
        
        # Enhancement-specific sections
        if is_enhancement:
            if report.implementation_details:
                lines.extend([
                    "## 🔧 Technical Implementation Details",
                    "",
                    report.implementation_details,
                    "",
                    "---",
                    "",
                ])
            
            if report.effort_estimate:
                lines.extend([
                    "## ⏱️ Effort Estimate",
                    "",
                    report.effort_estimate,
                    "",
                    "---",
                    "",
                ])
        
        # Impact assessment
        impact_title = "## 🎯 Scope & Impact" if is_enhancement else "## 💥 Blast Radius"
        lines.extend([
            impact_title,
            "",
            report.impact_assessment,
            "",
            "---",
            "",
            "## 📊 Confidence Assessment",
            "",
            f"**Confidence Level:** {int(report.confidence * 100)}%",
            "",
            f"**Reasoning:** {report.confidence_reason}",
            "",
            "---",
            "",
            "_This report was automatically generated by AI Engineering Investigator_",
        ])
        
        logger.info("Generated markdown report")
        return "\n".join(lines)
